README.md
Howdy. We successfully did the thing.
=> add hackathon names

index.html
=> add root div

css/style.css, index.html
=> add basic styles

components/Book.js
=> Update Book.js to include author and price

components/Navigation.js
Created Navigation component that passes piece of State.
=> Create Navigation component

index.js
Added Form to Render function.
=> Add Form to Render function 

index.js
Add link names with Books first.
=> Add link names

components/Footer.js
Created Footer.js in Components.
=> Create Footer export

css/style.css, index.js
Made the navigation bar slightly more visually stimulating.
=> Center, capitalized nav, and removed bulletpoints

css/style.css
The original color and layout scheme was inappropriate and hid the chosen text shadow. We modernized it.
=> Change h1 text, bg color, alignment

css/style.css
Resized the lasagna image and text.
=> Restrict image size and text alignment

components/Content.js
=> Refactor buildBooksHTML function to utilize map method

css/style.css, index.js
Moving on down. To the east side.
=> Move render to bottom of index.js

components/Form.js, index.js
Continuing to clean up code via refactoring.
=> Remove state from Footer.js

components/Book.js, components/Content.js, index.js, package-lock.json, package.json
Refactor Book.js to map() over the selling_points array, remove <figure> and <figcaption>
=> Refactor Book.js to use map

index.js
My linter went a little crazy.
=> Refactor States to use products with an array of books and albums

index.js
=> Refactor event listener for form

components/Form.js
=> Update form to add radio buttons for Books and Albums

components/Form.js
=> Add name value to each input

index.js
Kyle, Steve, and Paul. Three of Four.
=> Add imports to index.js.

form.js
=> Add form js and function to export form in file

components/Form.js, css/style.css, index.js, package-lock.json, package.json
Selling Points still needs handling.
=> Re Add code for form to add book to 'books' 

index.js
render(states); has been entered into the call back function.
=> Display new book on screen.

css/style.css
Submit and Clear button have improved. Some work can still be done.
=> Add new styles for form

css/style.css, index.js
We are starting on editing grid values after this pull
=> Put page in grid

README.md
=> Add names to savvy-coders-hackathon

README.md
<li>"Vanessa, Savion, Laura,  @Nyilah"</li>
=> Go Getters

index.html
=> add title for project

index.html
=> Add links and title to footer

README.md, index.html
=> Add sample card for book.

style.css
=> Create css for card 

components/Footer.js, index.html
=> create footer functional component

index.html
=> create root div in index.html

index.js
=> create render function for state

index.js
=> Manually add another book to state.
